# Generated by Django 5.2.6 on 2026-06-19 00:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BOMFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_role', models.CharField(choices=[('master', 'Master BOM'), ('optional', 'Optional BOM')], max_length=10)),
                ('file', models.FileField(upload_to='bom_files/%Y/%m/')),
                ('original_name', models.CharField(max_length=255)),
                ('file_format', models.CharField(choices=[('csv', 'CSV'), ('xlsx', 'Excel (XLSX)'), ('xls', 'Excel (XLS)'), ('json', 'JSON')], max_length=10)),
                ('file_size', models.PositiveBigIntegerField(default=0)),
                ('row_count', models.PositiveIntegerField(default=0)),
                ('column_count', models.PositiveIntegerField(default=0)),
                ('columns_detected', models.JSONField(default=list)),
                ('key_column_detected', models.CharField(blank=True, max_length=100)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('parse_error', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'BOM File',
                'verbose_name_plural': 'BOM Files',
                'ordering': ['file_role', 'uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='ComparisonSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Friendly name for this comparison', max_length=200)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('total_comparisons', models.PositiveIntegerField(default=0)),
                ('avg_match_score', models.FloatField(default=0.0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comparison_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Comparison Session',
                'verbose_name_plural': 'Comparison Sessions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ComparisonResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_column_used', models.CharField(blank=True, max_length=100)),
                ('common_columns', models.JSONField(default=list)),
                ('match_score', models.FloatField(default=0.0)),
                ('exact_match_count', models.PositiveIntegerField(default=0)),
                ('partial_match_count', models.PositiveIntegerField(default=0)),
                ('missing_count', models.PositiveIntegerField(default=0)),
                ('extra_count', models.PositiveIntegerField(default=0)),
                ('total_master_rows', models.PositiveIntegerField(default=0)),
                ('total_optional_rows', models.PositiveIntegerField(default=0)),
                ('result_data', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('master_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='as_master', to='comparison.bomfile')),
                ('optional_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='as_optional', to='comparison.bomfile')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='comparison.comparisonsession')),
            ],
            options={
                'verbose_name': 'Comparison Result',
                'verbose_name_plural': 'Comparison Results',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='bomfile',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='comparison.comparisonsession'),
        ),
    ]
