services:
  - type: web
    name: bom-comparison
    env: python
    plan: free
    rootDir: bom_tool
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --noinput && python manage.py migrate
    startCommand: gunicorn bom_tool.wsgi:application
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: false
      - key: ALLOWED_HOSTS
        value: bom-comparison.onrender.com
      - key: DATABASE_URL
        sync: false
